In [2]:
import numpy as np

**1**

In [3]:
a=np.array([1,2,3,4,5])
print(a)
b=a.copy()
b[4]=6
print(b)
print(b.base)

[1 2 3 4 5]
[1 2 3 4 6]
None


**2**



In [4]:
a=np.array([1,2,3,4,5])
print(a)
b=a.view()
b[4]=6
print(b)
print(b.base)

[1 2 3 4 5]
[1 2 3 4 6]
[1 2 3 4 6]


**3**

In [5]:
a=np.array([1,2,3,4])
b=a.copy()
c=a.view()
b[2]=5
c[3]=6
print(a)
print(b)
print(c)
print(b.base)
print(c.base)

[1 2 3 6]
[1 2 5 4]
[1 2 3 6]
None
[1 2 3 6]


**4**

In [6]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print()
b=a.view()
a[0,1]=9
print(b)
print()
print(a)


[[1 2 3 4]
 [5 6 7 8]]

[[1 9 3 4]
 [5 6 7 8]]

[[1 9 3 4]
 [5 6 7 8]]


**5**

In [7]:
a=np.array([1,2,3,4,5,6,7,8])
b=np.array(a[1:6])
print(b)
print(b.base)

[2 3 4 5 6]
None


**6**

In [8]:
a=np.array([1,2,3,4,5])
b=a.view()
c=np.may_share_memory(a,b)
print(c)

True


**7**

In [9]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3)
print(a)
print()
print(b)
print()
print(b.base)

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]


**8**

In [10]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a.shape)
print()
print(a.reshape(3,3))

(9,)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**9**

In [11]:
a=np.arange(1,13)
print(a)
print(a.shape)
print()
b=a.reshape(3,4)
print(b)
print(b.shape)
print()
c=b.reshape(2,3,2)
print(c)
print(c.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


**10**

In [12]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print()
b=a.reshape(2,6)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


**11**

In [13]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print()
b=a.reshape(2,2,2)
print(b)
print()
c=b.reshape(2,4)
print(c)

[[1 2 3 4]
 [5 6 7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[1 2 3 4]
 [5 6 7 8]]


**12**

In [14]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)
print()
b=a.reshape(2,8)
print(b)
print()
c=a.reshape(4,4)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


**13**

In [15]:
a=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(a)
print()
b=a.reshape(-1)
print(b)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


**14**

In [16]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in a:
  print(x)

[1 2 3]
[4 5 6]
[7 8 9]


**15**

In [17]:
a=np.array([[1,2,3],[4,5,6]])
for idx,x in np.ndenumerate(a):
  print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


**16**

In [18]:
a=np.array([[[1,2,3]],[[4,5,6]]])
for idx,x in np.ndenumerate(a):
  print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 0, 2) 6


**17**

In [19]:
a=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(a):
  print(x)

1
2
3
4
5
6
7
8


**18**

In [20]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for idx,x in np.ndenumerate(a):
  print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


**19**

In [21]:
a=np.array([1,2,3,4,5,6],ndmin=6)
print(a)
for x in np.nditer(a):
  print(x)

[[[[[[1 2 3 4 5 6]]]]]]
1
2
3
4
5
6


**20**

In [28]:
a=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(a,flags=['buffered'],op_dtypes=['float']):
  print(x)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0


**21**

In [23]:
a=np.array([[1,2,3,4],[5.2,6.4,7.3,8.5]])
for x in np.nditer(a):
  print(x)

1.0
2.0
3.0
4.0
5.2
6.4
7.3
8.5


**22**

In [29]:
a=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(a,flags=['buffered'],op_dtypes=['float']):
  print(x)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0


**23**

In [25]:
a=np.array([1,2,3,4,5,6,7,8,9])
for x in np.nditer(a[::2]):
  print(x)

1
3
5
7
9


**24**

In [33]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
b=a[0:,1:2]
for idx,x in np.ndenumerate(b):
  print(idx,x)

[[1 2 3 4]
 [5 6 7 8]]
(0, 0) 2
(1, 0) 6


 **25**

In [27]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
for idx,x in np.ndenumerate(a[0:2,:,1:2]):
  print(idx,x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(0, 0, 0) 2
(0, 1, 0) 5
(1, 0, 0) 8
(1, 1, 0) 11
